### ISSUE TITLE
Leftmost little arrow icons not showing

### ISSUE THREAD

**Issue by morovis** [Mangeshrex/vim-dots#1]
Hello, you dotfile is amazing mad props. I don't know if it's the type of nerdfont I am using (Have tried a few)  but the leftmost little arrows ont he left of the directories appear to me as broken icons specifically [ 0 F 0 / 3 5 D]. Do you know how can I fix it ? Thanks!

**Comment by Mangeshrex** [comment]
Hmm it could be the problem with the terminal emulator what nerd fonts are u using ? U can the ones from vimdevicons official repository. And try if that works.

**Comment by morovis** [comment]
Yup! it's the terminal. I had been using terminator. Read your comment and booted up vim in kitty just to see, and I can see them now. They're not arrows they're lines though, but I guess it's a terminal thing then not a system or config issue. 

I can't get over this vim config it's just like vscode layout but better. Time to change terminals. Thank you so much man

**Comment by Mangeshrex** [comment]
No worries buddy try alacritty it's the fastest terminal emulator for me alacritty takes milli seconds to launch check my bspwm-dotfiles repo in that onedark folder has alacritty config you can try that and modify as per your needs. 
Thank you :)
